### ISSUE TITLE
Doesn't compile on ubuntu 16.04

### ISSUE THREAD

**Issue by rcspam** [gnome-mpv/gnome-mpv#271]
Overview Description:
It doesn't compile...
My gtk3 lib version:
```
$ apt-cache madison libgtk3.0-cil-dev 
libgtk3.0-cil-dev |   2.99.3-2 | http://fr.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```
Steps to Reproduce:
1. git clone https://github.com/gnome-mpv/gnome-mpv
2. cd gnome-mpv && ./autogen.sh
3. make

Actual Results:

```
$ make
Making all in src
make[1] : on entre dans le répertoire « /home/xxx/SOURCE/gnome-mpv/src »
  GEN      mpris/gmpv_mpris_gdbus.c
  GEN      gmpv_marshal.c
  GEN      gmpv_marshal.h
  GEN      gmpv_authors.h
make  all-am
make[2] : on entre dans le répertoire « /home/xxx/SOURCE/gnome-mpv/src »
  CC       gnome_mpv-gmpv_main.o
  CC       gnome_mpv-gmpv_actionctl.o
  CC       gnome_mpv-gmpv_application.o
  CC       gnome_mpv-gmpv_common.o
  CC       gnome_mpv-gmpv_controller.o
  CC       gnome_mpv-gmpv_control_box.o
  CC       gnome_mpv-gmpv_file_chooser.o
gmpv_file_chooser.c: In function ‘gmpv_file_chooser_new’:
gmpv_file_chooser.c:87:2: error: not enough variable arguments to fit a sentinel [-Werror=format=]
  chooser = gtk_file_chooser_dialog_new(title, parent, action, NULL);
  ^
cc1: some warnings being treated as errors
Makefile:660 : la recette pour la cible « gnome_mpv-gmpv_file_chooser.o » a échouée
make[2]: *** [gnome_mpv-gmpv_file_chooser.o] Erreur 1
make[2] : on quitte le répertoire « /home/xxx/SOURCE/gnome-mpv/src »
Makefile:414 : la recette pour la cible « all » a échouée
make[1]: *** [all] Erreur 2
make[1] : on quitte le répertoire « /home/xxx/SOURCE/gnome-mpv/src »
Makefile:395 : la recette pour la cible « all-recursive » a échouée
make: *** [all-recursive] Erreur 1
```

Expected Results:

Version:

Additional Information:
